version: '3.8'

services:
  kitchen_website:
    build:
      context: ./kitchen_website
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:2c75533f72c9@db/website
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 6 && python kitchen_app.py"]  

  order_website:
    build:
      context: ./order_website
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:2c75533f72c9@db/website
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 6 && python order_app.py"]  

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2c75533f72c9
    volumes:
      - pg_data:/var/lib/postgresql/data  # To persist data

volumes:
  pg_data: